### PR TITLE
Add logo drawn by Allison Horst

### LINKED ISSUE #206: Add a hex sticker
My go-to is to incorporate a potoo somehow. I mean look at this fella:

image

### PR DESCRIPTION
**Pull request by hadley**
Fixes #206

### CODE REVIEW

**Comment by MichaelChirico** [comment]
what do we have to do here in terms of licensing/attribution? want to make sure Allison gets all due credit!

**Comment by hadley** [comment]
Could add a sentence to the readme explaining that the bird is a potoo, and that the logo was drawn by Allison?

**Comment by hadley** [comment]
Done. Let me know if there's a better place.

**Comment by MichaelChirico** [comment]
Trust your expertise/relative experience here. Thanks again!!

**Pull request merged**
